/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mx.edu.uaz.proyectodulceria.vista;
import static mx.edu.uaz.ingsoft.proyectodulceria.persistencia.entidades.ClaveAleatoria.claveP;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import mx.edu.uaz.ingsoft.proyectodulceria.persistencia.entidades.DetalleVentas;
import mx.edu.uaz.ingsoft.proyectodulceria.persistencia.modelo.dao.DetalleVentasDao;

/**
 *
 * @author dany_
 */
public class ReporteVentasForm extends javax.swing.JInternalFrame {
    DetalleVentasDao dvdao = new DetalleVentasDao();
    DetalleVentas dv = new DetalleVentas();
    DefaultTableModel modelo = new DefaultTableModel();
    
    void listar(){
        List <DetalleVentas> lista =dvdao.listar();
        modelo = (DefaultTableModel)tablaDetalle.getModel();
        
        Object[]ob=new Object[5];
        for (int i = 0; i < lista.size(); i++) {
            ob[0]=lista.get(i).getId();
            ob[1]=lista.get(i).getIdVentas();
            ob[2]=lista.get(i).getIdProducto();
            ob[3]=lista.get(i).getCantidad();
            ob[4]=lista.get(i).getPrecioVenta();
            modelo.addRow(ob);
        }
        tablaDetalle.setModel(modelo);
    }    

    /**
     * Creates new form ReporteVentasForm
     */
    public ReporteVentasForm() {
        initComponents();
        listar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDetalle = new javax.swing.JTable();
        cerrar = new javax.swing.JButton();

        setTitle("Reporte de ventas");

        tablaDetalle.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tablaDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "ID VENTAS", "CLAVE P", "CANTIDAD", "PRECIO VENTA"
            }
        ));
        jScrollPane1.setViewportView(tablaDetalle);

        cerrar.setText("X");
        cerrar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(453, 453, 453)
                .addComponent(cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cerrar)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_cerrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cerrar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaDetalle;
    // End of variables declaration//GEN-END:variables
}
